version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: babbeluser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: babbel
    ports:
      - '5432:5432'
    volumes:
      - addressbook-db:/var/lib/postgresql/data

  addressbook:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  addressbook-db:
